### ISSUE TITLE
post not published

### ISSUE THREAD

**Issue by shannonpileggi** [rweekly/rweekly.org#794]
Hi rweekly - thank you for all that you do!  I am a new contributer, and I noticed that my recent blog [post](https://www.pipinghotdata.com/posts/2020-10-25-your-first-r-package-in-1-hour/) published on Sunday 10/25 didn't make it in the 2020-43 issue on 10/25 or the 2020-44  issue on 11/1 (but it was registered in the live feed).  Are posts published on Sundays not eligible for inclusion?

**Comment by jonocarroll** [comment]
Hi, that's a great post and will surely be included in the next issue. Editors compile the new issue over the weekend so submissions posted after Friday (dependent on the editor's timezone) may end up in the following week's issue unless the editor happens to re-check. Thanks for the submission!

**Comment by shannonpileggi** [comment]
Awesome, thanks!  I'll remember to publish on weekdays moving forward.

**Comment by shannonpileggi** [comment]
Hi again - just flagging that my post did not make it into the 2020-45 issue on Nov 9 either.  :(  At this point, I am not requesting inclusion in the next issue though.  @maelle

**Comment by RobWHickman** [comment]
@shannonpileggi  this is absolutely my fault and I take full responsibility! I didn't see the closed issue so didn't know to include it otherwise I surely would have!  @ColinFay (who is the editor for the coming week) has been made aware so it should appear in the next issue.

**Comment by shannonpileggi** [comment]
No worries, I understand that I published at an awkward time for your editorial process!  And I very much appreciate all of your efforts to disseminate R knowledge.  :)

**Comment by shannonpileggi** [comment]
Hi again! 👋 I feel a bit silly to keep chasing this, but this post did not make it into 2020-46 (and of course, not 2020-47 either).  Would it be helpful if I re-submitted through a PR through the one-off sharing request, even though it came in through the RSS feed?

**Comment by jonmcalder** [comment]
So sorry @shannonpileggi! Like @RobWHickman, clearly both @ColinFay & I overlooked this in subsequent releases due to the issue remaining closed. Thanks @maelle for finally resolving it! 🤗

**Comment by shannonpileggi** [comment]
No problem, thanks again for persisting with me! 🤗
